run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - gocognit
    - goconst
    - gosec
    - revive
    - godot
    - gci
    - goimports
    - funlen
    - lll
    - gocritic
    - errorlint
    - gochecknoinits

linters-settings:
  gocognit:
    min-complexity: 15
  funlen:
    lines: 100
  lll:
    line-length: 120
  goconst:
    min-occurrences: 3
