# Golangci-lint configuration for k8s-pod-rightsizer
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - nonamedreturns
    - predeclared
    - revive
    - stylecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/wesleyemery/k8s-pod-rightsizer)
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '5'
      - '10'
      - '24'
      - '60'
      - '100'
      - '1000'
      - '1024'
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
    confidence: medium
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nestif:
    min-complexity: 4
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    confidence: 0
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  unparam:
    check-exported: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0