# Minimal golangci-lint configuration
# Use this for quick checks or when starting to fix issues
run:
  timeout: 5m

linters:
  enable:
    - errcheck     # Unchecked errors
    - govet        # Suspicious constructs
    - staticcheck  # Static analysis
    - ineffassign  # Ineffectual assignments
    - typecheck    # Type checking

issues:
  max-issues-per-linter: 100
  max-same-issues: 50


