---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rightsizing-k8s-rightsizer-io-v1alpha1-podrightsizing
  failurePolicy: Fail
  name: vpodrightsizing.rightsizing.k8s-rightsizer.io
  rules:
  - apiGroups:
    - rightsizing.k8s-rightsizer.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podrightsizings
  sideEffects: None
