# This rule is not used by the project pod-rightsizer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the rightsizing.k8s-rightsizer.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-rightsizer
    app.kubernetes.io/managed-by: kustomize
  name: podrightsizing-editor-role
rules:
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings/status
  verbs:
  - get
