apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-rightsizer
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings/finalizers
  verbs:
  - update
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings/status
  verbs:
  - get
  - patch
  - update