---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings/finalizers
  verbs:
  - update
- apiGroups:
  - rightsizing.k8s-rightsizer.io
  resources:
  - podrightsizings/status
  verbs:
  - get
  - patch
  - update
