apiVersion: rightsizing.k8s-rightsizer.io/v1alpha1
kind: PodRightSizing
metadata:
  labels:
    app.kubernetes.io/name: pod-rightsizer
    app.kubernetes.io/managed-by: kustomize
  name: podrightsizing-sample
  namespace: default
spec:
  target:
    namespace: default
    labelSelector:
      matchLabels:
        app: test-webapp
  analysisWindow: "1m"
  dryRun: true
  schedule: "*/5 * * * *"
  updatePolicy:
    strategy: manual
    maxUnavailable: "25%"
    minStabilityPeriod: "5m"
  thresholds:
    cpuUtilizationPercentile: 90
    memoryUtilizationPercentile: 90
    safetyMargin: 25
    minChangeThreshold: 10
    minCpu: 50m
    minMemory: 64Mi
    maxCpu: 2
    maxMemory: 2Gi
  metricsSource:
    type: prometheus
    prometheusConfig:
      url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"